# Generated by Django 3.0.7 on 2020-06-11 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicedb',
            name='total_tcc',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='invoicedb',
            name='total_vat',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
