# Generated by Django 3.0.7 on 2020-06-11 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0002_auto_20200611_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicedb',
            name='date',
            field=models.DateField(),
        ),
    ]
