# Generated by Django 3.0.7 on 2020-06-11 15:11

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('invoice', '0003_auto_20200611_1442'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='invoicedb',
            unique_together={('number', 'user')},
        ),
    ]
